Revert "[lsan] On Fuchsia, don't use atexit hook for leak checks"
This reverts commit 9150b1436924d6841b6bc4f01d5221597023bfa6.
This reverts commit bdd4a2c65ff971ffa55efc3d84e607eaaf0452ec.

Causes linker errors which were not fixed by the subsequent commit
either:

/home/nikic/llvm-project/compiler-rt/lib/asan/asan_rtl.cpp:503: error: undefined reference to '__asan::InstallAtExitCheckLeaks()'