Revert "Fix attr docs from previous no-unique-adderss change (#67195)"
This reverts commit 6425b1ad7a8926a3a8070529bf323691adf83293.

It caused
```
error: Record `NoUniqueAddress', field `Documentation' exists but does not have a list value
```