Revert "[lldb] Use nullptr instead of 0 or NULL (NFC)"
This reverts commit 3c60094cde48c2ebd853ea31652f9c41f5011bd5.

It again broke builds on Windows:

  lldb/source/Host/common/HostNativeThreadBase.cpp(37,14): error:
  assigning to 'lldb::thread_result_t' (aka 'unsigned int') from
  incompatible type 'std::nullptr_t'