Revert D130308 "[clang] extend getCommonSugaredType to merge sugar nodes"
This reverts commit 93d7519460927ca7a8acb275ead0a345712265a9.
There are multiple complaints on the review.

In addition, it may cause spurious
```
error: invalid operands to binary expression ('SinkPrinter' and 'char[cluster_name_length]')
note: candidate template ignored: substitution failure: variably modified type 'char *' cannot be used as a template argument SinkPrinter operator<<(const SinkPrinter &s, T) {
```
for some C++ code