Revert "ADT: SmallVector size/capacity use word-size integers when elements are small"
This reverts commit 3c098bf6bca82d772e6082bbca80f13aae923314.

clang-cmake-armv7-quick/llvm/llvm/lib/Support/SmallVector.cpp:81:22:
error: duplicate explicit instantiation of 'SmallVectorBase<unsigned int>'