Revert "Implement a new kind of Pass: dynamic pass pipeline"
This reverts commit d58b137e95386694c1e2c083500afd8c80660d3c.

Test  mlir/test/Pass:dynamic-pipeline-fail-on-parent.mlir.test fails
when run with ASAN:

ERROR: AddressSanitizer: stack-use-after-scope on address ...

Reviewed By: bkramer, pifon2a

Differential Revision: https://reviews.llvm.org/D88079