Revert "[InferAttrs] Add writeonly to all the math functions"
This reverts commit 20b2e52a5ac20935b40687735ae5b04a2820edfa and
20c23fe7e5c28e999217493ffa8296ee6d21f409.

That commit caused crashes with compilation e.g. like this
(not fixed by the follow-up commit):

$ cat sqrt.c
float a;
b() { sqrt(a); }
$ clang -target x86_64-linux-gnu -c -O2 sqrt.c
Attributes 'readnone and writeonly' are incompatible!
  %sqrtf = tail call float @sqrtf(float %0) #1
in function b
fatal error: error in backend: Broken function found, compilation aborted!