[RISCV] Fix a warning
This patch fixes:

  llvm/lib/Target/RISCV/GISel/RISCVCallLowering.cpp:590:19: error:
  unused variable 'F' [-Werror,-Wunused-variable]