Revert "[FPEnv][X86] Platform-specific builtin constrained FP enablement"
This reverts commit 26a8bd761b49f28fb7c96fff2c45815ab80bca93.

Tests fail:
error: unable to create target: 'No available targets are compatible with triple "x86_64-apple-darwin"'

This happens on clang-hexagon-elf, clang-cmake-armv7-quick, and
clang-cmake-armv7-quick bots.

If anyone has any suggestions on why then I'm all ears.

Differential Revision: https://reviews.llvm.org/D73570

Revert "[FPEnv][X86] Speculative fix for failures introduced by eda495426."

This reverts commit e0a1c1d6a9cd5f0a3c45b56d6d93e838e50f0db5.

The speculative fix didn't solve the test failures on Hexagon, ARMv6, and
MSVC AArch64.