Revert "[ADT] Support const-qualified unique_functions"
This reverts commit 1bd8ae289e3d010393f5650518ef1afdd6b54dba.

Breaks the build:

llvm/include/llvm/ADT/FunctionExtras.h:223:7: error: explicit template argument list not allowed
  223 |       Callbacks<CallableT, CalledAs, EnableIfTrivial<CallableT>>;