Revert "[RISCV][NFC] Make generated intrinsic records more human-readable (#133710)"
This reverts commit 7b3093c68a6fa165119734bb4bcca5123eaf972e.

Error: "declaration of ‘clang::RISCV::RequiredExtensions
{anonymous}::SemaRecord::RequiredExtensions’ changes meaning of
‘RequiredExtensions’ [-fpermissive]"