[SPIR-V] Add missing ScalarOpts library (#114384)
Fixes an "undefined reference to `llvm::createRegToMemWrapperPass()'"
linker error introduced by 343cec5b3b98 ("[SPIR-V] Fix BB ordering &
register lifetime (#111026)", 2024-10-30).