Revert "Use-after-return sanitizer binary metadata"
This reverts commit 094a3038ac6c2b63c26c5baf82acef7ecd005df8.

This patch results in:

  llvm/lib/CodeGen/SanitizerBinaryMetadata.cpp:57:17: error: no member
  named 'size' in 'llvm::MDTuple'