Fix mismerge with remote cache path error
When using the -fcasid-output option, even if a remote cache path is not
passed we can still see the error:

error: '-fcasid-output' is incompatible with remote caching backend

This patch fixes that bug

(cherry picked from commit 0a90143edf01b50082154223f05e26413f0c16db)