Revert [llvm] annotate ABIBreakingChecks symbols for DLL export (#147965)
This patch reverts commit bd5d3747fd66c84168c8cca2a14e69643f53534d. The
change introduced a cyclic dependency:
```
fatal error: cyclic dependency in module 'LLVM_Utils': LLVM_Utils -> LLVM_Config_ABI_Breaking -> LLVM_Utils
```

See failure log at
https://green.lab.llvm.org/job/llvm.org/job/clang-stage2-Rthinlto/976/console.