Revert "[lldb] Upstream support for Foundation constant classes"
This reverts commit ac8d2b5ac2f6a3d53ae18196d0fff279652cb4d3.

This breaks build bots witha  missing file:
/home/worker/2.0.1/lldb-x86_64-debian/llvm-project/lldb/source/Plugins/Language/ObjC/Cocoa.cpp:10:10: fatal error: 'objc/runtime.h' file not found