Revert "[lldb] [gdb-remote client] Refactor handling qSupported"
This reverts commit e4857aa5337706d5a6a72bfaba4960c918481a3f.

It fails to build, with errors such as:
  GDBRemoteCommunicationClient.cpp:1005:20:
  error: no viable overloaded '='
          avail_name = compression;