[bazel][libc][NFC] Add missing layering deps (#107947)
After f2eb4417cd11728bc854714006279fc670957076

e.g.

```
external/llvm-project/libc/test/src/math/smoke/NextTowardTest.h:12:10: error: module llvm-project//libc/test/src/math/smoke:nexttowardf_test does not depend on a module exporting 'src/__support/CPP/bit.h'
```