Revert "[LoopVectorizer] Inloop vector reductions"
This reverts commit 6154dbf38efe41d0008693403aac4492ac0cd8d5. It breaks the build:

```
~/src/llvm-project/llvm/lib/Analysis/IVDescriptors.cpp:868:10: error: no viable conversion from returned value of type 'SmallVector<[...], 8>' to function return type 'SmallVector<[...], 4>'
  return ReductionOperations;
```