Revert "Fix amdgpu-arch for dll name on Windows (#101350)"
This reverts commit 452c36a077a53ebfcfe2709dbe93979aee4c1ade.

Revert it due to breaking buildbot:

Z:\b\llvm-clang-x86_64-sie-win\llvm-project\clang\tools\amdgpu-arch\AMDGPUArchByHIP.cpp(104):
 error C2039: 'parse': is not a member of 'llvm::VersionTuple'

https://lab.llvm.org/buildbot/#/builders/46/builds/13184