Revert "[lld-macho] Avoid using bump-alloc in TrieBuider"
This reverts commit 18cc6b20a31ca93848b72fe057dee0bc46610228.

That commit breaks the build with errors of the form:

/usr/local/google/home/saugustine/llvm/llvm-project/lld/MachO/ExportTrie.cpp:148:11: error: definition of implicitly declared destructor
TrieNode::~TrieNode() {