Thread llvm::Expected through SwiftASTContext::Reconstruct type
all the way to the expression evaluator. Without this change a user
would see a misleading

  error: <EXPR>:8:1: cannot find 'variable' in scope

instead of pointing at the missing debug info for variable's type.

rdar://125613361
(cherry picked from commit 50d74309926077e4ba096cdbf025e2b6cf062db6)