Revert "Threading: Convert Optional to std::optional"
This reverts commit 464e7440939a1aec28ea399615e44c178dd55127.

This commit breaks the build for BOLT:
  bolt/lib/Profile/DataAggregator.cpp:264:66: error: no viable
  conversion from 'Optional<StringRef>[3]' to
  'ArrayRef<std::optional<StringRef>>'