[Driver] Fix a warning
This patch fixes:

  clang/lib/Driver/ToolChains/Darwin.cpp:2937:3: error: default label
  in switch which covers all enumeration values
  [-Werror,-Wcovered-switch-default]

(cherry picked from commit da6bbef1fa90fb270df2a43cfad6b07eada95b80)