Revert "[llvm] add zstd to llvm::compression namespace"
This reverts commit 038abe083cab612f020cd7e4e7e58e8c0b7a3639.

Breaks macOS builds with this:
llvm/lib/Support/Compression.cpp:24:10: fatal error: 'zstd.h' file not found