Revert "Add symbol locator time for each module in statistics (#134563)"
This reverts commit 7bf582fe16b242e95415953e0db9448713d3dc47.

Multiple buildbot failures have been reported:
https://github.com/llvm/llvm-project/pull/134563

The build fails with:

  lldb/source/Target/Statistics.cpp:75:39: error: use of undeclared
  identifier 'num_symbols_loaded'