[AArch64] Fix a warning
This patch fixes:

  llvm/lib/Target/AArch64/AArch64ISelLowering.cpp:6890:25: error:
  unused variable 'TLI' [-Werror,-Wunused-variable]