Temporarily revert "Add a facility to get system cache directory and use it in clangd"
This reverts commit ed287ad6f49c54abe47ee06826c3b503d7f27c34.

As it broke building the unittests:

.../sources/llvm-project/llvm/unittests/Support/Path.cpp:334:5: error: use of undeclared identifier 'set'
    set(Value);
    ^
1 error generated.