[flang][OpenMP] Remove unused variable (NFC)
llvm-project/flang/lib/Lower/OpenMP/ClauseProcessor.cpp:97:15:
error: unused variable 'allocatorOperand' [-Werror,-Wunused-variable]
  mlir::Value allocatorOperand;
              ^
1 error generated.