Revert "[mlir][tosa] Split tosa-to-linalg named ops out of pass"
This reverts commit 3fb9045e612f8fc63821d833decc02f292003167.

There is a missing CMake dependency, building with shared libraries is
broken:

55.509 [45/4/3061] Linking CXX shared library lib/libMLIRTosaToLinalg.so.14git
FAILED: lib/libMLIRTosaToLinalg.so.14git
...
TosaToLinalgPass.cpp: undefined reference to `mlir::createCanonicalizerPass()'