[BOLT] Fix a warning
This patch fixes:

  bolt/lib/Target/AArch64/AArch64MCSymbolizer.cpp:128:20: error:
  unused variable 'SymbolPageAddr' [-Werror,-Wunused-variable]