[bazel] Add missing deps for #141864 (#142437)
Added in b7cf630b059043cf44366f0e28150d978165aa99.

```
external/llvm-project/llvm/include/llvm/Frontend/Driver/CodeGenOptions.h:16:10: error: module llvm-project//llvm:FrontendDriver does not depend on a module exporting 'llvm/Support/Compiler.h'
#include "llvm/Support/Compiler.h"
```