Revert "[lld-macho] Fix symbol relocs handling for compact unwind's functionAddress"
This reverts commit 1263be53ea568e39227f4ec0f55c1736e010a646.

The commit in question causes:

  lld/MachO/InputFiles.cpp:916:13: error: use of undeclared identifier
  'it'