[rdar://116435579] Fix build failure.
The DIAG_SIZE_DRIVE value was increased to go past the following assertion:

llvm-project/clang/lib/Basic/DiagnosticIDs.cpp:161:1: error: static assertion failed due to requirement 'static_cast<unsigned int>(diag::NUM_BUILTIN_DRIVER_DIAGNOSTICS) < static_cast<unsigned int>(diag::DIAG_START_DRIVER) + static_cast<unsigned int>(diag::DIAG_SIZE_DRIVER)': DIAG_SIZE_DRIVER is insufficient to contain all diagnostics, it may need to be made larger in DiagnosticIDs.h.

The assertion was raised when merging the commit:

commit 0a44878e7b9e738f4a82a9a820aa4e5ddbe5afbe
Author: Alex Voicu <alexandru.voicu@amd.com>

    [HIP][Clang][Driver] Add Driver support for hipstdpar