Revert "[mlir][ODS] Use StringLiteral instead of StringRef when applicable"
This reverts commit 6cee7492b2592c20fe4c9f6230733e0ca988bd85 because
it breaks GCC 5 build:

  error: could not convert '(const char*)""' from 'const char*' to 'llvm::StringLiteral'
     static ::llvm::StringLiteral getDialectNamespace() { return ""; }