Revert "Remove redundant "std::move"s in return statements"
The build failed with

  error: call to deleted constructor of 'llvm::Error'

errors.

This reverts commit c67b59ff9d2f62108202af4346116fe93dce42aa.