Revert "[mlir][irdl] Support variadicity check in operations"
This reverts commit 8b5b5f20599e66e667c12ecdf76fdba05dc2eee1.

This is the error reported by the buildbot:
 /home/buildbots/ppc64le-flang-rhel-test/ppc64le-flang-rhel-clang-build/llvm-project/mlir/lib/Dialect/IRDL/IRDLLoading.cpp:97:22: error: no member named 'reduce' in namespace 'std'
  int32_t sum = std::reduce(denseSegmentSizes.asArrayRef().begin(),

Full details are available at:
    https://lab.llvm.org/buildbot#builders/21/builds/78689