Revert "Move DroppedVariableStatsIRTest.cpp to CodeGen folder"
This reverts commit 1aec2c2267f0935b54f6be7152b892a1483f378d.

Revert "Reland 614a43e8026fd6fa55bb7c3cc15af458c5d6c8a9 (#119650)"

This reverts commit 199dd4a4c288484f022cf7dcb54b90928f007313.

This is because the clang-ppc64le-linux-multistage bot breaks with error

undefined reference to `vtable for llvm::DroppedVariableStatsIR'