Improve error handling in SwiftUserExpression.
Previously this
```
$ swiftc test.swift -g -o test
$ lldb -o 'b main' -o 'b test' -o r -o 'e -i0 -- test()' ./test
(lldb) ^D
```

resulted in
```
Can't execute a swift expression without a runtime
UNREACHABLE executed at llvm-project/lldb/source/Plugins/ExpressionParser/Swift/SwiftUserExpression.cpp:90!
```

after this patch it's

```
(lldb) ^D
error: Could not finish swift expression because the process is being torn down
```

Unfortunately catching this error in a test case is tricky.

(cherry picked from commit 176b5d011d6b189084a0e7ad7928e02701f56e83)