[ADT] Fix an unused variable warning
This patch fixes:

  llvm/include/llvm/ADT/GenericUniformityImpl.h:752:8: error: unused
  variable 'printBlockSet' [-Werror,-Wunused-variable]