Revert "[LLD] [COFF] Implement a GNU/ELF like -wrap option"
This reverts commit 28426c79d296950d31ad1eabb3a7d23f76975ca3.

Breaks Windows builds.

C:\src\llvm-mint\lld\COFF\Symbols.cpp(26,1): error: static_assert failed due to requirement 'sizeof(lld::coff::SymbolUnion) <= 48' "symbols should be optimized for memory usage"
static_assert(sizeof(SymbolUnion) <= 48,