Revert "[MLIR][Presburger] introduce SetCoalescer"
This reverts commit 2f063a25cb26216e037e0d584de25e9d12927b7f.

The build is broken with some configurations (gcc-5 and gcc-8):

mlir/lib/Analysis/Presburger/PresburgerRelation.cpp:402:32: error: qualified name does not name a class before '{' token
 class presburger::SetCoalescer {