[IPO] Fix uused-variable warnings
This patch fixes:

  llvm/lib/Transforms/IPO/AttributorAttributes.cpp:2038:10: error:
  unused variable 'IsKnown' [-Werror,-Wunused-variable]