[libclang/python] Add missing concept declaration CursorKind (#69125)
Maps to
[`CXCursor_ConceptDecl`](https://github.com/llvm/llvm-project/blob/09a8e444484e246e042cc2827e5bd1cd08afd184/clang/include/clang-c/Index.h#L2716),
added in 09a8e444484e246e042cc2827e5bd1cd08afd184.

Without this I get this error on my codebase which uses C++20 concept
decls:
```
ValueError: Unknown template argument kind 604
```