Revert "Fix MLIR build failure: error: no member named 'getValue' in 'mlir::OptionalParseResult'"
This reverts commit ee448e38c86d0876dc7840b73134f0d9bb14a7a4.

A bot is broken