Revert "[clang] Implement Change scope of lambda trailing-return-type"
This reverts commit badc006652ed82a6d50c2926b4a02263b10111f4.
This broke clang bootstrap: it made existing C++ code in LLVM invalid:

llvm/include/llvm/CodeGen/LiveInterval.h:630:53: error: captured variable 'Idx' cannot appear here
              [=](std::remove_reference_t<decltype(*Idx)> V,
                                                    ^