[LoongArch] Fix -Wunused-variable in LoongArchExpandPseudoInsts.cpp (NFC)
llvm-project/llvm/lib/Target/LoongArch/LoongArchExpandPseudoInsts.cpp:480:20:
 error: unused variable 'MF' [-Werror,-Wunused-variable]
  MachineFunction *MF = MBB.getParent();
                   ^
1 error generated.

(cherry picked from commit 52d1397e38ee88b170585c9c824d08e6975890ca)
Change-Id: Icb5970367f4900cd96d6e9cf6a724b7ef0959a5e
(cherry picked from commit d50769aa6c042aa73e27d4ccf060f674c904eaf1)
Signed-off-by: Ami-zhang <zhanglimin@loongson.cn>