evert "[mlir] Limit Python dependency to Development.Module when possible."
This reverts commit 143aafe041623c730bcea27a292fb6595b5c5b5f.

The build is broken with errors like:

GPUPasses.cpp:(.text.pybind11_object_init[pybind11_object_init]+0x118): undefined reference to `PyExc_TypeError'