[clang][examples] Remove unused variable 'key' in LLVMPrintFunctionNames.cpp (NFC)
/llvm-project/clang/examples/LLVMPrintFunctionNames/LLVMPrintFunctionNames.cpp:33:28: error: unused variable 'key' [-Werror,-Wunused-variable]
  static llvm::AnalysisKey key;
                           ^
1 error generated.