Revert "[compiler-rt] Avoid memintrinsic calls inserted by the compiler"
This reverts commit 5f4d8867488b849454066ce61eed9b2c019ed983.

Fails on Mac OS with "sanitizer_libc.cpp:109:5: error: aliases are not
supported on darwin".