Revert "[Tooling/Inclusion] Handle std::get symbol."
This reverts commit 95cfc88bc1f23005dfd293dd1215b9db3e51dd37.

Causing many clangd test breakages, similar to:

error: no matching constructor for initialization of 'llvm::SmallVector<clang::tooling::stdlib::Header>'
                : llvm::SmallVector<clang::tooling::stdlib::Header>(
                  ^