Revert "Move DroppedVariableStats to CodeGen lib (#120650)"
This reverts commit 79465c3fe2eba8e364fc081a41b2a3308d8a9d62.

Broke bot ppc64le-clang-multistage-test:

undefined reference to
`llvm::DroppedVariableStats::populateVarIDSetAndInlinedMap in
In function `llvm::DroppedVariableStatsIR::visitEveryInstruction