Revert "[llvm-exegesis] Add thread IDs to subprocess memory names (#84451)"
This reverts commit 98d89f059b3263b69f8e4b6c8468239846d10fa2.

This breaks building LLVM on macOS, failing with

    llvm/tools/llvm-exegesis/lib/SubprocessMemory.cpp:146:33: error: out-of-line definition of 'setupAuxiliaryMemoryInSubprocess' does not match any declaration in 'llvm::exegesis::SubprocessMemory'
    Expected<int> SubprocessMemory::setupAuxiliaryMemoryInSubprocess(